# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dUSkPZd327sFYkA=,iv:b63fjV5YwvRFP4I1+AaCo58l6shCzh3ln6O816Aj+FI=,tag:1rvsQNA58Po6vslETjvtzg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ge+LA2gnQAnb4lw5ZNteQT6n15pbw3K5Bw==,iv:LVxMzj3IcYY0NqsiMSm4KI8EZDSEsIgsniLzE0pjDzg=,tag:nGWuSwz6njC1h7COyDfwnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURWVoZnlvM0t4Sm4yZnVq
            TGdpcVpmTTdwQ2lHM2N6cTdXZ0tQQnBVbTJVCktud0NZUHhiL1gxRWtVRG5rcDh3
            YWVlMmhoUFp4bWMxaFByU2h3SnRXUzAKLS0tIEgvZlRqN2pVVklITXB2Qm42M2lB
            b0U2NFBUY3dxUzJtRlJ3ams1WkUxUXcK1JEkP3ruig9V1Xg7yiYKTRZbObYlatzU
            2/1ALDGw4QrXRc685BdbsFPb4jfTIAN71JjMt1MUFTr9ODp26K7J6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T14:24:45Z"
    mac: ENC[AES256_GCM,data:+X6kBRAkX+bxOomNOJg3prjGjedM7fD4SxryCZaFyWJjajCtT/A+NO2rOKtNauQGxnJF2XuHDkaNeinZK0s4vC+CbiK+dOEi87KCai78NDtlh9+/R31azNWm5IH7bNxBlPnmF1hJ76A3hNXwsfm40nxUS+iost/wXTK/gsU6ZwM=,iv:mvP+P9na649am6sWEhpXG9DaKEvbGqLPVjyzc2p5WFw=,tag:7uhIEjldU/BV66TyLk107w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
